name: release package
on:
  push:
    branches:
      - main

jobs:
  release-package:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: "16"
    - name: Install Yarn
      run: npm install -g yarn
    - name: check node version
      run: node -v
    - name: Install modules
      run: yarn install --frozen-lockfile
    - name: Publish
      run: |
        git config user.name Dominik Ager
        git config user.email d.ager@alpin11.com
        git pull
        npm version patch
        git push
        npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
