name: release package
on:
  push:
    branches:
      - main

jobs:
  release-package:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: 16
        registry-url: https://npm.pkg.github.com/
    - name: Run install
      uses: borales/actions-yarn@v4
      with:
        cmd: install --frozen-lockfile
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    - name: Patch version
      run: |
        git config user.name Dominik Ager
        git config user.email d.ager@alpin11.com
        git pull
        yarn version --patch
        git push
    - name: Publish
      run: npm publish 
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  
