name: release package
on:
  push:
    branches:
      - main

jobs:
  release-package:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - uses: bahmutov/npm-install@v1

    - run: |
        git config user.name Johann Berger
        git config user.email j.berger@alpin11.com
        git pull
        npm version patch
        git push
        npm publish
