name: release package
on:
  push:
    branches:
      - main

jobs:
  release-package:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: "16"
    - name: check node version
      run: node -v
    - name: Run install
      uses: borales/actions-yarn@v4
      with:
        cmd: install --frozen-lockfile
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    - name: Publish
      run: |
        git config user.name Dominik Ager
        git config user.email d.ager@alpin11.com
        git pull
        npm version patch
        git push
        npm publish --userconfig=./.npmrc --registry=https://npm.pkg.github.com/
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
